# Generated by Django 3.0.7 on 2020-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyID', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.IntegerField(choices=[(0, 'Sale'), (1, 'Rent')], default=0)),
                ('images', models.ImageField(blank=True, upload_to='properties/%Y/%m/%d')),
                ('details', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
