# Generated by Django 3.0.7 on 2020-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200611_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='BA',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='BDS',
            field=models.CharField(max_length=5),
        ),
    ]
