# Generated by Django 3.0.7 on 2020-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200611_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=20),
        ),
    ]
