# Generated by Django 3.0.7 on 2020-06-16 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200611_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='details',
        ),
        migrations.AddField(
            model_name='property',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('OTHERS', 'Others')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentID', models.IntegerField()),
                ('agentFname', models.CharField(max_length=200)),
                ('agentLname', models.CharField(max_length=200)),
                ('contactNum', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('emailAddr', models.EmailField(max_length=300)),
                ('requirements', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('pID', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='property.Property')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
