# Generated by Django 3.0.7 on 2020-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='zipcode',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
