# Generated by Django 3.0.7 on 2020-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200611_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=20),
        ),
    ]
